// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/types.go

// Package storagemock is a generated GoMock package.
package storagemock

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	storage "github.com/shaj13/raftkit/internal/storage"
	raftpb "go.etcd.io/etcd/raft/v3/raftpb"
)

// MockSnapshotter is a mock of Snapshotter interface.
type MockSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotterMockRecorder
}

// MockSnapshotterMockRecorder is the mock recorder for MockSnapshotter.
type MockSnapshotterMockRecorder struct {
	mock *MockSnapshotter
}

// NewMockSnapshotter creates a new mock instance.
func NewMockSnapshotter(ctrl *gomock.Controller) *MockSnapshotter {
	mock := &MockSnapshotter{ctrl: ctrl}
	mock.recorder = &MockSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotter) EXPECT() *MockSnapshotterMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockSnapshotter) Read(snap raftpb.Snapshot) (*storage.SnapshotFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", snap)
	ret0, _ := ret[0].(*storage.SnapshotFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockSnapshotterMockRecorder) Read(snap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockSnapshotter)(nil).Read), snap)
}

// ReadFromPath mocks base method.
func (m *MockSnapshotter) ReadFromPath(path string) (*storage.SnapshotFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFromPath", path)
	ret0, _ := ret[0].(*storage.SnapshotFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFromPath indicates an expected call of ReadFromPath.
func (mr *MockSnapshotterMockRecorder) ReadFromPath(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFromPath", reflect.TypeOf((*MockSnapshotter)(nil).ReadFromPath), path)
}

// Reader mocks base method.
func (m *MockSnapshotter) Reader(arg0 raftpb.Snapshot) (string, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reader indicates an expected call of Reader.
func (mr *MockSnapshotterMockRecorder) Reader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockSnapshotter)(nil).Reader), arg0)
}

// Write mocks base method.
func (m *MockSnapshotter) Write(sf *storage.SnapshotFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", sf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockSnapshotterMockRecorder) Write(sf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSnapshotter)(nil).Write), sf)
}

// Writer mocks base method.
func (m *MockSnapshotter) Writer(arg0 string) (io.WriteCloser, func() (raftpb.Snapshot, error), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Writer", arg0)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(func() (raftpb.Snapshot, error))
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Writer indicates an expected call of Writer.
func (mr *MockSnapshotterMockRecorder) Writer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Writer", reflect.TypeOf((*MockSnapshotter)(nil).Writer), arg0)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Boot mocks base method.
func (m *MockStorage) Boot(meta []byte) ([]byte, raftpb.HardState, []raftpb.Entry, *storage.SnapshotFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Boot", meta)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(raftpb.HardState)
	ret2, _ := ret[2].([]raftpb.Entry)
	ret3, _ := ret[3].(*storage.SnapshotFile)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// Boot indicates an expected call of Boot.
func (mr *MockStorageMockRecorder) Boot(meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Boot", reflect.TypeOf((*MockStorage)(nil).Boot), meta)
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// Exist mocks base method.
func (m *MockStorage) Exist() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exist")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Exist indicates an expected call of Exist.
func (mr *MockStorageMockRecorder) Exist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockStorage)(nil).Exist))
}

// SaveEntries mocks base method.
func (m *MockStorage) SaveEntries(st raftpb.HardState, entries []raftpb.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntries", st, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntries indicates an expected call of SaveEntries.
func (mr *MockStorageMockRecorder) SaveEntries(st, entries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntries", reflect.TypeOf((*MockStorage)(nil).SaveEntries), st, entries)
}

// SaveSnapshot mocks base method.
func (m *MockStorage) SaveSnapshot(snap raftpb.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSnapshot", snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSnapshot indicates an expected call of SaveSnapshot.
func (mr *MockStorageMockRecorder) SaveSnapshot(snap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSnapshot", reflect.TypeOf((*MockStorage)(nil).SaveSnapshot), snap)
}

// Snapshotter mocks base method.
func (m *MockStorage) Snapshotter() storage.Snapshotter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshotter")
	ret0, _ := ret[0].(storage.Snapshotter)
	return ret0
}

// Snapshotter indicates an expected call of Snapshotter.
func (mr *MockStorageMockRecorder) Snapshotter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshotter", reflect.TypeOf((*MockStorage)(nil).Snapshotter))
}
