// Code generated by MockGen. DO NOT EDIT.
// Source: internal/raftengine/engine.go

// Package raftenginemock is a generated GoMock package.
package raftenginemock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	raftengine "github.com/rakoo/raft/internal/raftengine"
	raftpb "github.com/rakoo/raft/internal/raftpb"
	raft "go.etcd.io/etcd/raft/v3"
	raftpb0 "go.etcd.io/etcd/raft/v3/raftpb"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockEngine) CreateSnapshot() (raftpb0.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot")
	ret0, _ := ret[0].(raftpb0.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockEngineMockRecorder) CreateSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockEngine)(nil).CreateSnapshot))
}

// LinearizableRead mocks base method.
func (m *MockEngine) LinearizableRead(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinearizableRead", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinearizableRead indicates an expected call of LinearizableRead.
func (mr *MockEngineMockRecorder) LinearizableRead(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinearizableRead", reflect.TypeOf((*MockEngine)(nil).LinearizableRead), ctx)
}

// ProposeConfChange mocks base method.
func (m_2 *MockEngine) ProposeConfChange(ctx context.Context, m *raftpb.Member, t raftpb0.ConfChangeType) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ProposeConfChange", ctx, m, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProposeConfChange indicates an expected call of ProposeConfChange.
func (mr *MockEngineMockRecorder) ProposeConfChange(ctx, m, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeConfChange", reflect.TypeOf((*MockEngine)(nil).ProposeConfChange), ctx, m, t)
}

// ProposeReplicate mocks base method.
func (m *MockEngine) ProposeReplicate(ctx context.Context, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposeReplicate", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProposeReplicate indicates an expected call of ProposeReplicate.
func (mr *MockEngineMockRecorder) ProposeReplicate(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeReplicate", reflect.TypeOf((*MockEngine)(nil).ProposeReplicate), ctx, data)
}

// Push mocks base method.
func (m_2 *MockEngine) Push(m raftpb0.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Push", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockEngineMockRecorder) Push(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockEngine)(nil).Push), m)
}

// ReportShutdown mocks base method.
func (m *MockEngine) ReportShutdown(id uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportShutdown", id)
}

// ReportShutdown indicates an expected call of ReportShutdown.
func (mr *MockEngineMockRecorder) ReportShutdown(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportShutdown", reflect.TypeOf((*MockEngine)(nil).ReportShutdown), id)
}

// ReportSnapshot mocks base method.
func (m *MockEngine) ReportSnapshot(id uint64, status raft.SnapshotStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportSnapshot", id, status)
}

// ReportSnapshot indicates an expected call of ReportSnapshot.
func (mr *MockEngineMockRecorder) ReportSnapshot(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportSnapshot", reflect.TypeOf((*MockEngine)(nil).ReportSnapshot), id, status)
}

// ReportUnreachable mocks base method.
func (m *MockEngine) ReportUnreachable(id uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportUnreachable", id)
}

// ReportUnreachable indicates an expected call of ReportUnreachable.
func (mr *MockEngineMockRecorder) ReportUnreachable(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportUnreachable", reflect.TypeOf((*MockEngine)(nil).ReportUnreachable), id)
}

// Shutdown mocks base method.
func (m *MockEngine) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockEngineMockRecorder) Shutdown(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockEngine)(nil).Shutdown), arg0)
}

// Start mocks base method.
func (m *MockEngine) Start(addr string, oprs ...raftengine.Operator) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{addr}
	for _, a := range oprs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Start", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEngineMockRecorder) Start(addr interface{}, oprs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{addr}, oprs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEngine)(nil).Start), varargs...)
}

// Status mocks base method.
func (m *MockEngine) Status() (raft.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(raft.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockEngineMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockEngine)(nil).Status))
}

// TransferLeadership mocks base method.
func (m *MockEngine) TransferLeadership(arg0 context.Context, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferLeadership", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferLeadership indicates an expected call of TransferLeadership.
func (mr *MockEngineMockRecorder) TransferLeadership(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferLeadership", reflect.TypeOf((*MockEngine)(nil).TransferLeadership), arg0, arg1)
}
